(require 'init_helm)
(require 'init_haskell)
(require 'init_regex)
(require 'init_prolog)
(require 'init_scheme)
(require 'init_magit)
(require 'init_imaxima)
(require 'init_proof_general)
; (require 'init_tramp)
; (require 'init_psgml)
(require 'init_yatex)
(require 'init_snippet)
; (require 'init_skk)
(require 'init_dired)
(require 'init_idris)
(require 'init_agda2)
(require 'init_scala)
(require 'init_hamlet)
(require 'init_sml)
;(require 'init_powerline)
;(require 'init_egison)
(require 'init_e2wm)
(require 'init_singular)
(require 'init_CoCoA)
(require 'init_markdown)
(provide 'init_main)
