[package]
name = "install-dotfiles"
version = "0.1.0"
authors = ["Hiromi ISHII <konn.jinro@gmail.com>"]

[dependencies]
serde        = "1.0"
serde_yaml   = "0.8"
serde_derive = "1.0"
glob         = "0.2"
itertools    = "0.7"
